In [15]:
bd = sorted(map(lambda x: tuple([x.split('|')[0], x.split('|')[1], int(x.split('|')[2])]), open("first_task.txt", "r").read().split("\n")))
for u in bd:
    print (f"{u[0]} {u[1]} - {u[2]}")

user_list = {}
for index, user in enumerate(bd):
    if user[0] not in user_list:
        user_list[user[0]] = {}

    if user[1] not in user_list[user[0]]:
        user_list[user[0]][user[1]] = 0

    user_list[user[0]][user[1]] += user[2]

for key in sorted(user_list):
    print (f"{key} { user_list[key]}")

Anna Metelskaya apple - 5
Anna Metelskaya banana - 1
Anna Metelskaya lemon - 5
Anna Metelskaya orange - 3
Anna Metelskaya pear - 2
Veronika Bogdanovich apple - 3
Veronika Bogdanovich banana - 2
Veronika Bogdanovich orange - 4
Veronika Bogdanovich pear - 7
Anna Metelskaya {'apple': 5, 'banana': 1, 'lemon': 5, 'orange': 3, 'pear': 2}
Veronika Bogdanovich {'apple': 3, 'banana': 2, 'orange': 4, 'pear': 7}


In [16]:
f = open("second_task.txt", "r")
n = int(f.readline())
files = {}
for i in range(n):
    temp = f.readline().split()
    files[temp[0]] = temp[1:]
print(files)
m = int(f.readline())
for i in range(m):
    temp = f.readline().split()
    if temp[1] in files[temp[0]]:
        print("OK")
    else:
        print("Access denied")
f.close()

{'file1': ['R', 'W'], 'file2': ['R', 'W', 'X'], 'file3': ['W', 'X'], 'file4': ['W']}
OK
OK
OK
OK
Access denied
OK
Access denied
Access denied


In [19]:
import numpy as np

n, m = map(int, input("Enter n, m: ").split())
print(n, m)
matrix = np.array([
    [
        m if i == j else (
            m - abs(i - j) if m - abs(i - j) >= n and m >= n else (
                -abs(i - j) - n if m - abs(i - j) < n <= m else (
                    m + abs(i - j) if m + abs(i - j) <= n and m < n else (
                        -2 * m - abs(i - j) + n if m + abs(i - j) > n > m else 999))))
        for j in range(n)
    ]
    for i in range(n)
])
print(matrix)

Enter n, m: 8 4
8 4
[[ 4  5  6  7  8 -5 -6 -7]
 [ 5  4  5  6  7  8 -5 -6]
 [ 6  5  4  5  6  7  8 -5]
 [ 7  6  5  4  5  6  7  8]
 [ 8  7  6  5  4  5  6  7]
 [-5  8  7  6  5  4  5  6]
 [-6 -5  8  7  6  5  4  5]
 [-7 -6 -5  8  7  6  5  4]]
